name: Deployment to DigitalOcean Droplet

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Load NVM environment
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ~/cpsquare/src/tiktok-chat-reader-server

            echo "Node version: $(node -v)"

            git pull origin master
            nvm use 22.11.0
            pm2 restart tiktok-chat-reader-server || pm2 start "node server.js" --name tiktok-chat-reader-server
            pm2 save
          EOF
